### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by thibautjombart** [richfitz/ring#9]
# Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions in R help
- [x] **Examples** for all exported functions in R Help that run successfully locally
- [ ] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and `URL`, `Maintainer` and `BugReports` fields in DESCRIPTION. **Contribution guidelines missing**

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed. **No performance claim**.
- [x] **Automated tests:** Unit tests cover essential functions of the package
   and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines **Not checked - see comments**.

#### Final approval (post-review)

- [x] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing: 

~2-3h

---

#### Vignettes

The main vignette does a good job of going through the functionalities of the package. The online version is a welcome addition. I have the following comments:

- The target audience could be mentioned in the introduction of the main vignette, e.g. "If you don't know what a ring buffer is, you don't need this package." (or whatever is appropriate). If it is meant for non-experts, either a quick explanation (with a diagram), or probably better just a link to the wikipedia page would be useful.

- This is not specific to this package, but by default the vignette will not be installed when using `github_install`, so that `vignette("ring")` will not work. It would be useful to provide instructions to fix this in the ..README.md`.

- Only one vignette is mentioned in the `README.md`

- The implementaion of `head` and `tail` will likely confuse peope unfamiliar with the concept of ring buffer. Again, maybe they have no point reading this.

- Typo in main vignette: "*This empies the buffer*" (talking about reset).

- Typo in main vignette: "*This empies the buffer*" (talking about reset).

- Second vignette: interesting stuff, but seems like some of this code could almost be part of the package, or (probably better) another (`ring+`?) package. I suspect that's what will happen if someone has a use for this.

#### Misc comments

- This is cool!

- As a curiosity, I'd like to see the memory and computational overhead of using byte buffers vs vectors.

- There are no guidelines for contributions.

- Package has 100% coverage and passes *goodpractices*.

- The file `push.R` is empty.

- Open quick inspection, the code is clear and decently annotated overal. Some bits may be a bit too sparse annotation wise: https://github.com/richfitz/ring/blob/master/R/ring_buffer_env.R#L223-L471

- Seeing `utils.R`, and having seen similar things I am wondering if it wouldn't be worse packaging these and similar bits into something.

**Comment by richfitz** [comment]
Great - thanks a lot @thibautjombart; will go through this probably next week and get things fixed up.

Re: `utils.R`; I see the point of packaging this stuff, but CRAN is littered with assertion packages already and I'm loathe to either add mine to the mess or to depend on any of the ones there (last that I looked most were not quite what I was looking for, had too many dependencies, or were not things that I necessarily trusted not to change their API).  The duplication is not ideal (and especially not the duplication of testing).

The second vignette _was_ part of the package!  I pulled it out because I decided that mixing side-effect driven storage with syntactic sugar that makes it look like normal R was potentially dangerous.  Basically, I wasn't totally happy with the design and compromises so wanted to make it a demo rather than something people would depend on so that if I _did_ want to use something like this I'd get a chance to break the API without causing anyone problems.  Will think more on how to present it (or decide if it should be just dropped)

**Comment by thibautjombart** [comment]
OK got you. I would not put it back into the pkg, you've kind of convinced me that packages as implementation of a specific task is the way to go, in most instances, but especially here. I would think this would be a `enhance` package, but probably overkill at this stage. Maybe you could just explain the above in two sentences in intro of the 2nd vignette?

**Comment by richfitz** [comment]
Yup, will do.  It's always interesting to see what sticks out, as I'd totally forgotten what I'd written and why

**Comment by richfitz** [comment]
I think that I've got it all now @thibautjombart; could you take another look when you get a moment

**Comment by thibautjombart** [comment]
Yes cool! :)
